spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: PaladinFrom!335
    driverClassName: org.postgresql.Driver
  main:
    lazy-initialization: true
#db.host=ec2-34-252-216-149.eu-west-1.compute.amazonaws.com
#db.db=d8bf4eb40dgo9m